services:
  front:
    image: ${DOCKER_IMAGE}
    container_name: ${DOCKER_CONTAINER}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${DOCKER_PORT}:80"
    volumes:
      - ${DOCKER_MOUNTED}:/mounted
